In [3]:
import numpy as np # Numpy kurulumu

In [5]:
data_list = [1,2,3]
data_list

[1, 2, 3]

In [7]:
arr = np.array(data_list)
arr

array([1, 2, 3])

In [8]:
data_list2 = [[1,2,3],[4,5,6],[7,8,9]]

In [11]:
arr2 = np.array(data_list2)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
arr3 = np.array([1,2,3])
arr3

array([1, 2, 3])

In [16]:
arr3[0] # arr3 ün ilk elemanı

1

In [17]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
arr2[2,2] # arr2 matrisindeki 2. satır ve 2. sütuna denk gelen sayı

9

In [19]:
arr2[0,1]

2

In [20]:
np.arange(1,10) # 1 den 10 a kadar olan değerleri sıralayan numpy komutu

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.arange(0,100,3) # 0'dan 100'e 3'er 3'er artan sayı dizisi

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [22]:
np.zeros(10) # 10 tane sıfır

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
np.ones(10) # 10 tane bir

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
np.linspace(0,100,5) # 0'dan 100'e 5 parçaya bölen kod

array([  0.,  25.,  50.,  75., 100.])

In [25]:
np.linspace(0,1,6) # 0'dan 1'e 6 parçaya bölen kod

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [27]:
np.eye(5) # 5 birimlik matris oluşturur

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
np.random.randint(1,10) # 1'den 10'a kadar rastgele sayı üreten numpy kodu

1

In [39]:
np.random.randint(1,10,5) # 1'den 10'a kadar 5 tane rastgele sayı üretip, bu sayılardan array oluşturan numpy kodu

array([8, 1, 6, 4, 7])

In [40]:
np.random.rand(5) # 0 ile 1 arasında rastgele 5 float değer üretip, bu değerlerden array oluşturan numpy kodu

array([0.56434854, 0.577684  , 0.93982619, 0.81692487, 0.88650414])